# https://www.netlifycms.org/docs/widgets/#select
backend:
  name: github
  repo: zobozdravstvo-ogrin/zobozdravstvo-ogrin.si
  branch: master
  base_url: https://github.zobozdravstvo-ogrin.si

slug:
  encoding: "ascii"
  clean_accents: true

# publish_mode: editorial_workflow
media_folder: "pages/images/uploads"
public_folder: "images/uploads"

collections:
  - name: "authors"
    label: "Authors"
    folder: "pages/author"
    description: "Author descriptions"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "author-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Image", name: "author_image", widget: "image", required: false}
      - {label: "Cover Image", name: "author_cover_image", widget: "image", required: false}

  - name: "clanki"
    label: "Clanki"
    folder: "pages/clanki"
    create: true
    filter: {field: "language", value: "sl"}
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Jezik", name: "language", widget: "select", options: [{ label: "English", value: "en" }, { label: "Slovenščina", value: "sl" }], default: "sl"}
      - label: "Avtor objave"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Pod naslov", name: "sub_title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Vsebina", name: "body", widget: "markdown"}
      - {label: "Datum objave", name: "date", widget: "datetime"}
      - {label: "Objavljeno", name: "published", widget: "boolean", default: true}
      - {label: "Naslovna fotografija", name: "image", widget: "image", required: false}
      - label: "Galerija"
        name: "galleryImages"
        required: false
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Začetna stran"
        description: "Začetna stran"
        file: "pages/index.md"
        extension: "md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "homepage"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Content", name: "body", widget: "markdown"}
          - {label: "Cover Image", name: "image", widget: "image", required: false}
          - label: "Sections"
            name: sections
            required: false
            widget: "object"
            fields:
            - label: "Section"
              name: "section"
              widget: "list"
              fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "KeyName", name: "keyname", widget: "string"}
              - {label: "Content", name: "body", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image", required: false}
          - label: "Front slideshow"
            name: frontslideshow
            widget: "object"
            fields:
            - label: "Slide"
              name: "slide"
              widget: "list"
              fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: true}
          - label: "Gallery"
            name: "gallery"
            required: false
            widget: "list"
            fields:
            - {label: "Title", name: "alt", widget: "string"}
            - {label: "Width", name: "width", widget: number}
            - {label: "Height", name: "height", widget: number}
            - {label: "Image", name: "src", widget: "image", required: false}
      - name: "ordinacija"
        label: "Kdo smo"
        description: "Kdo smo"
        file: "pages/ordinacija.md"
        extension: "md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Content", name: "body", widget: "markdown"}
          - label: "PrependJS"
            name: "prependJs"
            allow_add: true
            widget: "list"
          - label: "Section"
            name: "section"
            required: false
            widget: "list"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "KeyName", name: "keyname", widget: "string"}
            - {label: "Content", name: "body", widget: "markdown"}
            - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Cover Image", name: "image", widget: "image", required: false}
          - label: "Slideshow"
            name: slideshow
            widget: "object"
            fields:
            - label: "Slide"
              name: "slide"
              widget: "list"
              fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: true}
      - name: "storitve"
        label: "Storitve"
        description: "Informacije o storitvah"
        file: "pages/storitve.md"
        extension: "md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Content", name: "body", widget: "markdown"}
          - label: "Section"
            name: "section"
            required: false
            widget: "list"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "KeyName", name: "keyname", widget: "string"}
            - {label: "Content", name: "body", widget: "markdown"}
            - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Cover Image", name: "image", widget: "image", required: false}
      - name: "narocanje"
        label: "Naročanje"
        description: "Informacije o naročanju"
        file: "pages/narocanje.md"
        extension: "md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "order"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Content", name: "body", widget: "markdown"}
          - label: "Section"
            name: "section"
            required: false
            widget: "list"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "KeyName", name: "keyname", widget: "string"}
            - {label: "Content", name: "body", widget: "markdown"}
            - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Cover Image", name: "image", widget: "image", required: false}
      - name: "kontakt"
        label: "Kontakt"
        description: "Kontakt in lokacija"
        file: "pages/kontakt.md"
        extension: "md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "PrependJS"
            name: "prependJs"
            allow_add: true
            widget: "list"
          - {label: "Content", name: "body", widget: "markdown"}
          - label: "Section"
            name: "section"
            required: false
            widget: "list"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "KeyName", name: "keyname", widget: "string"}
            - {label: "Content", name: "body", widget: "markdown"}
            - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Cover Image", name: "image", widget: "image", required: false}
  - name: "settings"
    label: "Settings"
    delete: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "pages/settings.json"
        description: "General Site Settings"
        editor:
          preview: false
        fields:
          - {label: "Site title", name: "site_title", widget: "string"}
          - {label: "Short title", name: "short_title", widget: "string"}
          - {label: "Site author", name: "site_author", widget: "string"}
          - {label: "Site author url", name: "site_author_url", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telephone", name: "tel", widget: "string"}
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - label: "Avtor objave"
                name: "author"
                widget: "relation"
                collection: "authors"
                searchFields: ["title"]
                valueField: ["title", "description", "body", "author_image"]
                displayFields: ["title"]
          - {label: "Contact", name: "contact", widget: "markdown"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
          - label: "Footer"
            name: footer
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Body", name: "body", widget: "text"}
              - {label: "Copy", name: "copy", widget: "string"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
